import { OurTeamData } from '../types';

export const MOCK_OUR_TEAM: OurTeamData = {
  heading: 'Tim & Praktisi Sinemus',
  subheading: 'Para profesional dan sineas di balik pengembangan ekosistem.',
  members: [
    // Executive Leadership (Board of Directors)
    {
      id: 'exec-ceo',
      name: 'Ahmad Fauzi',
      role: 'Chief Executive Officer (CEO)',
      department: 'EXECUTIVE',
      departmentBadge: 'CEO',
      isExecutive: true,
      photoUrl: '/images/khoas_poster.png',
      bio: 'Memimpin visi strategis, ekspansi bisnis, dan tata kelola ekosistem Sinemus Indonesia.',
      skills: ['Strategic Leadership', 'Corporate Vision', 'Business Expansion'],
    },
    {
      id: 'exec-cao',
      name: 'Siti Rahma',
      role: 'Chief Administrative Officer (CAO)',
      department: 'EXECUTIVE',
      departmentBadge: 'CAO',
      isExecutive: true,
      photoUrl: '/images/khoas_poster.png',
      bio: 'Bertanggung jawab atas manajemen operasional, tata kelola legal, dan pengembangan HR.',
      skills: ['Operations', 'Legal Compliance', 'HR Governance'],
    },
    {
      id: 'exec-cfo',
      name: 'Rian Hidayat',
      role: 'Chief Financial Officer (CFO)',
      department: 'EXECUTIVE',
      departmentBadge: 'CFO',
      isExecutive: true,
      photoUrl: '/images/khoas_poster.png',
      bio: 'Mengelola strategi keuangan perusahaan, alokasi kapital, dan perencanaan anggaran.',
      skills: ['Financial Strategy', 'Capital Allocation', 'Budgeting'],
    },
    {
      id: 'exec-cto',
      name: 'Budi Santoso',
      role: 'Chief Technology Officer (CTO)',
      department: 'EXECUTIVE',
      departmentBadge: 'CTO',
      isExecutive: true,
      photoUrl: '/images/khoas_poster.png',
      bio: 'Memimpin riset teknologi sinema, infrastruktur digital, dan arsitektur platform.',
      skills: ['Cinema Tech', 'System Architecture', 'Digital Infrastructure'],
    },
    {
      id: 'exec-cmo',
      name: 'Dewi Lestari',
      role: 'Chief Marketing Officer (CMO)',
      department: 'EXECUTIVE',
      departmentBadge: 'CMO',
      isExecutive: true,
      photoUrl: '/images/khoas_poster.png',
      bio: 'Mengarahkan strategi branding, kampanye pemasaran, dan pertumbuhan komunitas sineas.',
      skills: ['Brand Strategy', 'Growth Marketing', 'Community Engagement'],
    },

    // Operational & Staff Team
    {
      id: 'staff-cao-1',
      name: 'Andi Permana',
      role: 'Staff CAO - Legal & Ops',
      department: 'OPERATIONS',
      photoUrl: '/images/khoas_poster.png',
      bio: 'Pendukung operasional dan pengawasan kepatuhan legalitas produksi.',
      skills: ['Legal Support', 'Ops Compliance'],
    },
    {
      id: 'staff-cfo-1',
      name: 'Nia Karmila',
      role: 'Staff CFO - Accounting',
      department: 'FINANCE',
      photoUrl: '/images/khoas_poster.png',
      bio: 'Spesialis pembukuan keuangan dan pelaporan akuntansi produksi.',
      skills: ['Accounting', 'Financial Tracking'],
    },
    {
      id: 'staff-cto-1',
      name: 'Rizky Pratama',
      role: 'Staff CTO - Systems',
      department: 'ENGINEERING',
      photoUrl: '/images/khoas_poster.png',
      bio: 'Pemeliharaan sistem platform digital dan pengembang infrastruktur streaming.',
      skills: ['Fullstack Dev', 'Streaming Pipeline'],
    },
    {
      id: 'staff-cmo-1',
      name: 'Maya Indah',
      role: 'Staff CMO - Media & Growth',
      department: 'MARKETING',
      photoUrl: '/images/khoas_poster.png',
      bio: 'Koordinator media sosial, promosi event sinema, dan manajemen publikasi.',
      skills: ['Social Media', 'Content Strategy'],
    },

    // Operational & Staff Team
    {
      id: 'unit-pud-1',
      name: 'Hendra Wijaya',
      role: 'Production Unit Director (PUD)',
      department: 'PRODUCTION',
      photoUrl: '/images/khoas_poster.png',
      bio: 'Pengarah unit produksi lapangan dan dokumentasi acara sinematik.',
      skills: ['Live Production', 'Unit Director'],
    },
    {
      id: 'unit-uco-1',
      name: 'Fajar Nugraha',
      role: 'Unit Chief Officer (UCO)',
      department: 'PRODUCTION',
      photoUrl: '/images/khoas_poster.png',
      bio: 'Supervisor teknis lapangan dan koordinator peralatan produksi sinema.',
      skills: ['Technical Lead', 'On-site Supervisor'],
    },
    {
      id: 'unit-abc-1',
      name: 'Fajar Nugraha',
      role: 'Unit Chief Officer (UCO)',
      department: 'MARKETING',
      photoUrl: '/images/khoas_poster.png',
      bio: 'Supervisor teknis lapangan dan koordinator peralatan produksi sinema.',
      skills: ['Technical Lead', 'On-site Supervisor'],
    },
  ],
};
