import { PortfolioItem } from '../types';

export const MOCK_PORTFOLIO_ITEMS: PortfolioItem[] = [
  {
    id: 'port-1',
    title: 'KHOAS SHORT MOVIE',
    category: 'Film',
    categoryLabel: 'Short Movie',
    year: '2024',
    director: 'Sinemus x Madrasah Pena',
    thumbnailUrl: '/images/khoas_poster.png',
    synopsis: 'Kolaborasi Sinemus Indonesia x Madrasah Pena dengan Ikatan Pelajar Putri PERSIS.',
    unitSlug: 'production',
  },
  {
    id: 'port-2',
    title: 'SANG KETUA',
    category: 'Film',
    categoryLabel: 'Feature Film',
    year: '2024',
    director: 'Sinemus Production',
    thumbnailUrl: '/images/khoas_poster.png',
    synopsis: 'Kisah drama kepemimpinan inspiratif di tengah dinamika perjuangan masyarakat.',
    unitSlug: 'production',
  },
  {
    id: 'port-3',
    title: 'CAHAYA DI BALIK AWAN',
    category: 'Series',
    categoryLabel: 'Original Series',
    year: '2024',
    director: 'Sinemus Screen',
    thumbnailUrl: '/images/khoas_poster.png',
    synopsis: 'Serial drama sinematik tentang harapan dan pengorbanan anak bangsa.',
    unitSlug: 'screen',
  },
  {
    id: 'port-4',
    title: 'AL-KAUTSAR',
    category: 'Documentary',
    categoryLabel: 'Dokumenter',
    year: '2024',
    director: 'Sinemus Academy',
    thumbnailUrl: '/images/khoas_poster.png',
    synopsis: 'Eksplorasi jejak peradaban dan keindahan spiritual di pelosok Nusantara.',
    unitSlug: 'academy',
  },
  {
    id: 'port-5',
    title: 'HIDAYAH',
    category: 'Film',
    categoryLabel: 'Feature Film',
    year: '2025',
    director: 'Sinemus Production',
    thumbnailUrl: '/images/khoas_poster.png',
    synopsis: 'Perjalanan reflektif menemukan kedamaian dan makna sejati kehidupan.',
    unitSlug: 'production',
  },
];


