import { CollaboratorPartnersData } from '../types';

export const MOCK_COLLABORATOR_PARTNERS: CollaboratorPartnersData = {
  heading: 'EKOSISTEM & JARINGAN KERJASAMA',
  subheading: 'Bersama para institusi, komunitas, dan vendor profesional dalam memajukan industri sinema Indonesia.',
  collaboratorsHeading: 'Mitra & Kolaborator Strategis',
  collaboratorsSubheading: 'Jejaring institusi pemerintah, akademisi, dan komunitas independen yang berkolaborasi dalam karya & riset.',
  vendorsHeading: 'Mitra Vendor & Produksi',
  vendorsSubheading: 'Dukungan teknis, persewaan peralatan, dan studio kreatif terbaik untuk kualitas produksi standar industri.',
  collaborators: [
    {
      id: 'collab-1',
      name: 'Pemkab Bandung',
      category: 'Pemerintah & Daerah',
      logoUrl: '/images/collaborators/kabupaten-bdg.PNG',
      description: 'Kemitraan strategis pengembangan potensi perfilman dan kebudayaan daerah.',
    },
    {
      id: 'collab-2',
      name: 'Universitas Islam Bandung',
      category: 'Akademisi & Universitas',
      logoUrl: '/images/collaborators/unisba.png',
      description: 'Kolaborasi akademis, inkubasi talenta, dan riset sinematografi.',
    },
    {
      id: 'collab-3',
      name: 'LDK Salman ITB',
      category: 'Institusi Pendidikan',
      logoUrl: '/images/collaborators/salman-itb.png',
      description: 'Jejaring pengembangan karya media kreatif dan edukasi pemuda.',
    },
    {
      id: 'collab-4',
      name: 'DPD KNPI',
      category: 'Organisasi Kepemudaan',
      logoUrl: '/images/collaborators/knpi.png',
      description: 'Sinergi pemberdayaan generasi muda melalui karya audio-visual.',
    },
    {
      id: 'collab-5',
      name: 'IPPI',
      category: 'Organisasi Pemuda',
      logoUrl: '/images/collaborators/ippi.png',
      description: 'Jaringan kemitraan pemuda-pemudi kreatif Indonesia.',
    },
    {
      id: 'collab-6',
      name: 'Pemuda PERSIS',
      category: 'Organisasi Masyarakat',
      logoUrl: '/images/collaborators/persis.png',
      description: 'Dukungan ekosistem dakwah kreatif dan media sinema universal.',
    },
    {
      id: 'collab-7',
      name: 'Motiva Cinema',
      category: 'Kolektif Cinema',
      logoUrl: '/images/collaborators/motiva-cinema.PNG',
      description: 'Kolaborasi produksi dan eksibisi sinema naratif independen.',
    },
    {
      id: 'collab-8',
      name: 'Tajdid TV',
      category: 'Media & Broadcasting',
      logoUrl: '/images/collaborators/tajdid-tv.png',
      description: 'Kemitraan penyiaran dan penayangan konten audio-visual berkemajuan.',
    },
    {
      id: 'collab-9',
      name: 'Madrasah Pena',
      category: 'Komunitas Literasi',
      logoUrl: '/images/collaborators/madrasah-pena.png',
      description: 'Riset penulisan narasi dan pengembangan skenario film.',
    },
    {
      id: 'collab-10',
      name: 'Sinemus Film Academy',
      category: 'Edukasi Sinema',
      logoUrl: '/images/collaborators/sfa.png',
      description: 'Program inkubasi dan pelatihan sinematografi bagi talenta muda.',
    },
  ],
  vendors: [
    {
      id: 'vendor-1',
      name: 'Ucup Rental',
      category: 'Camera & Lighting Rental',
      logoUrl: '/images/vendor/ucup-rental.png',
      description: 'Penyedia armada peralatan kamera, lensa, dan pencahayaan standar bioskop.',
    },
    {
      id: 'vendor-2',
      name: 'Artnarki Studio',
      category: 'Creative & Art Studio',
      logoUrl: '/images/vendor/artnarki.png',
      description: 'Mitra desain artistik, seni visual, dan tata panggung sinematik.',
    },
    {
      id: 'vendor-3',
      name: 'BSM Production',
      category: 'Technical Vendor',
      logoUrl: '/images/vendor/bsm.png',
      description: 'Dukungan sistem teknis dan pendukung operasional lapangan.',
    },
    {
      id: 'vendor-4',
      name: 'Lumps Graphic',
      category: 'Post-Production & Graphic',
      logoUrl: '/images/vendor/lumps.png',
      description: 'Layanan desain grafis, identitas visual, dan pos-produksi.',
    },
  ],
};

